
let User = function (username, password, id) {
    this.id = id;
    this.username = username;
    this.password = password;
}

User.prototype.save = function (callback) {
    let self = this;
    if (self.id == undefined) {
        // new record
        self.db.run('insert into users(username, password) values(?, ?)', 
            self.username, self.password, 
            function (err, result) {
                if (err) return callback(err);
                self.id = this.lastID;  // this.lastID holds autogenerated primary key
                console.log("New id: ", self.id);
                callback();
            });

    } else {
        // update existing record
        this.db.run('update users set username = ?, password = ? where id = ?', 
            this.username, this.password, self.id, 
            function (err, result) {
                if (err) return callback(err);
                callback(null, result); 
            });
    }
}

User.findByUsername = function (username, callback) {
    User.db.get('select * from users where username = ?', username, function(err, data) {
        if (err) return callback(err);
        if (data) {
            console.log("Got: ", data);
            callback(null, new User(data.username, data.password, data.id));
        } else {
            callback(null, null);
        }
    });
}

module.exports = function(db) {
    User.db = User.prototype.db = db; // expose db to User class and instances
    return User;
}
